### ISSUE TITLE
data upload

### ISSUE THREAD

**Issue by leoniethomas** [datascience-mobi/2021-topic-03-team-03#2]
Hey ihr! 
Ich hab gesehen dass bei euch die Daten im repo hochgepushed wurden. Da die Daten vertraulich sind und das repo hier öffentlich, wäre es gut wenn ihr diese wieder runter nehmt! 
Wenn ihr eure Daten in dem repo liegen haben wollt wo ihr auch die Scripte liegen habt, dann solltet ihr ein .gitignore file in das repo machen damit die Daten nicht mithochgepushed werden. 
Gruppe 4 hat so ein file schon erstellt, also könnt ihr ja villeicht auch eure Komulitonen um Rat fragen. 
Ansonsten findet ihr auch genug anleitungen wenn ihr einfach ".gitignore file git" googled (z.B. https://www.pluralsight.com/guides/how-to-use-gitignore-file)

**Comment by BiancaKaifer** [comment]
Hi Leonie und Gruppe,
Also ich hab jz mal ein .gitignore erstellt
Also ich habe es so verstanden dass das lediglich bewirkt, dass Änderungen die in den darin aufgeführten Dokumenten vorgenommen wurden nicht mehr weiter aktualisiert werden
Daher hab ich jz vorerst nur diese Dateien eingefügt:
.DS_Store (wird bei Mac OS automatisch erstellt von git mit hochgeladen und ist nicht wirklich sinnvoll für uns zum teilen)
.Rhistory (müssen wir auch nicht teilen wenn wir ordentlich kommentieren was wir gemacht haben)

Ich könnte zwar noch die Tabelle einfügen aber soweit ich das jetzt verstanden hab ändert das nichts an der Verfügbarkeit sondern eben nur wenn jemand direkt Änderungen daran vornehmen sollte dass diese mit aktualisiert werden

Daher die Frage konnte bisher jeder die Tabelle mit den Daten öffnen ? 
Könnten wir sie dann nicht auch einfach aus dem respiratory entfernen?
und müssten wir dann nicht auch eine andere Speichermöglichkeit für das Markdown file finden?

Sry für die lange Nachricht aber ich dachte so sind meine Überlegungen vielleicht besser nachvollziehbar

**Comment by BiancaKaifer** [comment]
war mir nicht ganz sicher inwiefern Du (Leonie) Ändeungen/Kommentare mitbekommst

habe es selbst eig nur über die E-Mail von github mitbekommen dass hier etwas gesendet wurde

**Comment by BiancaKaifer** [comment]
Hab glaub ich aber grade verstanden was du gemeint hattest
vllt kannst du dir ja nochmal das .gitignore file anschauen ob das jz so passt

Habe noch zusätzlich ergänzt:
.RData
.Rproj.user/
--> dies Ergänzungen sollen soweit ich das jetzt gelesen habe schonmal präventiv probleme verhindern die bei gitHub und R in verbindung auftreten können und beide enthalten keine wichtigen daten

**Comment by leoniethomas** [comment]
Ja das sieht gut aus jtzt :+1:

**Comment by Khalida-D** [comment]
<img width="611" alt="Bildschirmfoto 2021-04-28 um 18 06 31" src="https://user-images.githubusercontent.com/82515668/116437050-4e079500-a84d-11eb-8870-52e261868df7.png">
Irgendwie funktioniert es nicht mehr

**Comment by leoniethomas** [comment]
liegen die Daten in deinem lokalen Folder drin ? oder hast du sie dort auch gelöscht ?

**Comment by Khalida-D** [comment]
Wo kriege ich den Zugriff drauf?
Es hatte alles davor gut funktioniert 
Jetzt nicht mehr

**Comment by Khalida-D** [comment]
hat jetzt funktioniert

**Comment by BiancaKaifer** [comment]
"liegen die Daten in deinem lokalen Folder drin ? oder hast du sie dort auch gelöscht"
-> hatte es iwi bei allen gelöscht dadurch dass ich es gitignore hinzugefügt hatte
-> hab es dann jedoch dort rausgenommen und den anderen gesagt dass sie es wieder runterladen sollen
