### ISSUE TITLE
Treffen heute git probleme

### ISSUE THREAD

**Issue by leoniethomas** [datascience-mobi/2021-topic-03-team-03#6]
Wann würde es euch den passen heute ? bei mir wäre so ab halb 5 gut.

**Comment by helenaweinig** [comment]
Hey vielen dank für die Möglichkeit würde fünf auch gehen? Falls nicht würde halb fünf auch passen.

LG Helena

Von meinem iPhone gesendet

**Comment by leoniethomas** [comment]
jup 5 Uhr passt mir gut. Alles gut, dafür bin ich ja da :)
